I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 146, in script call
    call camera_knight_attack
  File "game/script.rpy", line 146, in script call
    call camera_knight_attack
ScriptError: could not find label 'camera_knight_attack'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 146, in script call
    call camera_knight_attack
  File "C:\Users\Jurya\Documents\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 146, in script call
    call camera_knight_attack
  File "C:\Users\Jurya\Documents\RenPy\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'camera_knight_attack'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Skeletonknight 1.0
Fri Mar 17 08:40:28 2023
